"""update sc

Revision ID: f39a84e57a94
Revises: 21eb3a2e7489
Create Date: 2021-01-07 20:55:47.567581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f39a84e57a94'
down_revision = '21eb3a2e7489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sales_id')
    )
    op.create_table('items',
    sa.Column('items_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.sales_id'], ),
    sa.PrimaryKeyConstraint('items_id')
    )
    op.drop_table('point_of_sales')
    op.alter_column('application_profile', 'application_profile_logo_data',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('application_profile', 'application_profile_logo_name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('application_profile', 'application_profile_logo_name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('application_profile', 'application_profile_logo_data',
               existing_type=sa.BLOB(),
               nullable=False)
    op.create_table('point_of_sales',
    sa.Column('point_of_sales_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('point_of_sales_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('items')
    op.drop_table('sales')
    # ### end Alembic commands ###
